// <auto-generated />
using System;
using BonosCalculadora.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BonosCalculadora.Migrations.DbBonos
{
    [DbContext(typeof(DbBonosContext))]
    partial class DbBonosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BonosCalculadora.Models.Calculadora", b =>
                {
                    b.Property<int>("CalculadoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cavali")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<double>("Cok")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<double>("Colocación")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<double>("Estructuración")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Flotacion")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<double>("ImRenta")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("NAños")
                        .HasColumnType("int")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<double>("Prima")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<double>("Vcomercial")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<double>("Vnominal")
                        .HasColumnType("float")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("CalculadoraId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Calculadora");
                });

            modelBuilder.Entity("BonosCalculadora.Models.Capitalizacion", b =>
                {
                    b.Property<int>("CapitalizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculadoraId")
                        .HasColumnType("int");

                    b.Property<string>("NCapitalizacion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CapitalizacionId");

                    b.HasIndex("CalculadoraId");

                    b.ToTable("Capitalizacion");
                });

            modelBuilder.Entity("BonosCalculadora.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BonosCalculadora.Models.DiasAño", b =>
                {
                    b.Property<int>("DiasAñoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculadoraId")
                        .HasColumnType("int");

                    b.Property<int>("Dias")
                        .HasColumnType("int")
                        .HasMaxLength(9)
                        .IsUnicode(false);

                    b.HasKey("DiasAñoId");

                    b.HasIndex("CalculadoraId");

                    b.ToTable("DiasAño");
                });

            modelBuilder.Entity("BonosCalculadora.Models.FrecuenciaPago", b =>
                {
                    b.Property<int>("FrecuenciaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculadoraId")
                        .HasColumnType("int");

                    b.Property<int>("Diasfrecuencia")
                        .HasColumnType("int")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Tipofrecuencia")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("FrecuenciaPagoId");

                    b.HasIndex("CalculadoraId");

                    b.ToTable("FrecuenciaPago");
                });

            modelBuilder.Entity("BonosCalculadora.Models.Historial", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("HistorialId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Historial");
                });

            modelBuilder.Entity("BonosCalculadora.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculadoraId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMetodo")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("MetodoPagoId");

                    b.HasIndex("CalculadoraId");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("BonosCalculadora.Models.TasaInteres", b =>
                {
                    b.Property<int>("TasaInteresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CalculadoraId")
                        .HasColumnType("int");

                    b.Property<double>("Tasa")
                        .HasColumnType("float")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Tipotasa")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("TasaInteresId");

                    b.HasIndex("CalculadoraId");

                    b.ToTable("TasaInteres");
                });

            modelBuilder.Entity("BonosCalculadora.Models.Calculadora", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Cliente", "Cliente")
                        .WithMany("Calculadora")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK_Calculadora_Ciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BonosCalculadora.Models.Capitalizacion", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Calculadora", "Calculadora")
                        .WithMany("Capitalizacion")
                        .HasForeignKey("CalculadoraId")
                        .HasConstraintName("FK_Capitalizacion_Calculadora");
                });

            modelBuilder.Entity("BonosCalculadora.Models.DiasAño", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Calculadora", "Calculadora")
                        .WithMany("DiasAño")
                        .HasForeignKey("CalculadoraId")
                        .HasConstraintName("FK_DiasAño_Calculadora");
                });

            modelBuilder.Entity("BonosCalculadora.Models.FrecuenciaPago", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Calculadora", "Calculadora")
                        .WithMany("FrecuenciaPago")
                        .HasForeignKey("CalculadoraId")
                        .HasConstraintName("FK_FrecuenciaPago_Calculadora");
                });

            modelBuilder.Entity("BonosCalculadora.Models.Historial", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Cliente", "Cliente")
                        .WithMany("Historial")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK_Historial_Ciente");
                });

            modelBuilder.Entity("BonosCalculadora.Models.MetodoPago", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Calculadora", "Calculadora")
                        .WithMany("MetodoPago")
                        .HasForeignKey("CalculadoraId")
                        .HasConstraintName("FK_MetodoPago_Calculadora");
                });

            modelBuilder.Entity("BonosCalculadora.Models.TasaInteres", b =>
                {
                    b.HasOne("BonosCalculadora.Models.Calculadora", "Calculadora")
                        .WithMany("TasaInteres")
                        .HasForeignKey("CalculadoraId")
                        .HasConstraintName("FK_TasaInteres_Calculadora");
                });
#pragma warning restore 612, 618
        }
    }
}
